### ISSUE TITLE
maximum recursion depth exceeded while calling a Python object

### ISSUE THREAD

**Issue by sfc-gh-rkato** [get-select/dbt-snowflake-monitoring#122]
I try to use this in dbt cloud.
I can see previews, but  run is occured following Error.

```
RecursionError: maximum recursion depth exceeded while calling a Python object
04:57:45  Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '33b00294-65e8-45cc-94ff-836c34bb6ebd', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7f8544066c70>]}
```

**Comment by NiallRees** [comment]
Hi, are you trying to run this project as-is vs installing it as a package?

**Comment by sfc-gh-rkato** [comment]
I am trying  to run this project as-is.
I used Dbt cloud's Github integration to get the repository in and run.

**Comment by NiallRees** [comment]
> I am trying to run this project as-is. I used Dbt cloud's Github integration to get the repository in and run.

Got it. This package can't be run directly as a project without getting the above error, unfortunately. I've not been able to track down why that is (it's a pretty cryptic error!)

**Comment by sfc-gh-rkato** [comment]
I understand, I try to package.
To use it as a package, do I just run dbt deps on the project I Clone from Github?

Or should I use the following process?
https://select.dev/docs/dbt-snowflake-monitoring/quickstart
https://select.dev/docs/dbt-snowflake-monitoring/example-usage

**Comment by NiallRees** [comment]
> I understand, I try to package. To use it as a package, do I just run dbt deps on the project I Clone from Github?
> 
> Or should I use the following process? https://select.dev/docs/dbt-snowflake-monitoring/quickstart https://select.dev/docs/dbt-snowflake-monitoring/example-usage

To use it as a package you’ll need an existing dbt project. See https://docs.getdbt.com/docs/build/packages

I’m going to close this issue now because the package isn’t intended to be run directly.
