### ISSUE TITLE
Seeking Help with Implementation Deps + Recursion errors

### ISSUE THREAD

**Issue by sfc-gh-rbacastow** [get-select/dbt-snowflake-monitoring#126]
Hello!
I'm encountering a few errors when trying to use the library with python 3.9 and 3.10 where both the dependencies and the runtime seem to fail. First dbt deps:

```bash
dbt deps                   
16:47:27  Running with dbt=1.6.0
16:47:28  Encountered an error:
Could not find a matching compatible version for package get-select/dbt_snowflake_query_tags
  Requested range: >=4.0.0, <5.0.0
  Compatible versions: ['1.0.0', '1.1.0', '1.1.1', '1.1.2', '1.1.3', '2.0.0', '2.0.1', '2.0.2', '2.1.0', '2.2.0', '2.3.0']

  Not shown: package versions incompatible with installed version of dbt-core
  To include them, run 'dbt --no-version-check deps'
  ```
  
  Then, when adjusting to run with 2.3.0 version to test that, I get the same error for each model:
 ```bash
 dbt run                                    
22:24:21  Running with dbt=1.6.0
22:24:22  Registered adapter: snowflake=1.6.0
22:24:24  Found 26 models, 2 tests, 12 sources, 0 exposures, 0 metrics, 499 macros, 0 groups, 0 semantic models
22:24:24  
22:24:27  Concurrency: 1 threads (target='dev')
22:24:27  
22:24:27  1 of 26 START sql incremental model ARCHIVE.stg_access_history ................. [RUN]
22:24:27  Unhandled error while executing 
maximum recursion depth exceeded
```

I was curious if we might be able to connect on this as I am demonstrating this work as a great usage of DBT + Snowflake together while intro-ing some of the great work Select is doing for Snowflake clients.

**Comment by ian-whitestone** [comment]
Hey @sfc-gh-rbacastow ! thanks for reaching out. Based on this error it sounds like you are trying to run the package from this repo, rather than from another dbt project (which is the intended usage).

> I was curious if we might be able to connect on this as I am demonstrating this work as a great usage of DBT + Snowflake together while intro-ing some of the great work Select is doing for Snowflake clients.

I'd be happy to chat anytime! Here's my availability https://calendly.com/ian-at-select/30min
