### ISSUE TITLE
Is there a way to only load the current month/year data from snowflake?

### ISSUE THREAD

**Issue by albertwangnz** [get-select/dbt-snowflake-monitoring#130]
Hi

I read the code and realized that the first full load will read all snowflake queries and other info into the stg tables.

I wonder if there is a way to only read the current month or the current year data?

Or is there a potential enhancement can do it?

Thank you.

Regards,
Albert

**Comment by ian-whitestone** [comment]
Hey @albertwangnz! This is not currently supported, and we don't have plans to support this since it is so cheap to process the full year of data the first time the model runs (we're talking <$5).

Is cost the main concern for you of this one time load? Or is there another factor?

**Comment by albertwangnz** [comment]
Hi @ian-whitestone Thank you for your quick response. Just to confirm that the corresponding snowflake tables, used by the dbt package, all only store recent 1 year data?

Thank you.

Regards,
Albert

**Comment by ian-whitestone** [comment]
That's right!

**Comment by albertwangnz** [comment]
Thanks a lot, @ian-whitestone .
