### ISSUE TITLE
❓ Question around query_tag configuration

### ISSUE THREAD

**Issue by bdtoole** [get-select/dbt-snowflake-monitoring#132]
No issue, but a couple questions around the configuration of the query tags. Creating as an issue in here for more public visibility per a request from @ian-whitestone.

The quickstart documentation says to `First, make sure to remove any existing +query_tag: dbt from your dbt_project.yml`. How does this work if the main project does not have any `+query_tag` specifications, but third-party packages set the query tag and the query tag gets set in a profiles.yml?

For example, the `snowplow_web` package has its own `snowplow__query_tag: "snowplow_dbt"` variable. How will the setting in `dbt-snowflake-monitoring` interact with Snowplow's own package variable? Do we also need to add an override for `snowplow__query_tag` in our main package?

Similarly, if we have `query_tag:` specified in our profiles.yml file, do we need to remove it from there, as well, to avoid any potential conflicts between the configurations when running our dbt models locally?

**Comment by NiallRees** [comment]
Hi @bdtoole, thanks for the questions.
1. In the case of a package setting the query tags for its models (if they're not a mapping type), you should just see the [warning here](https://github.com/get-select/dbt-snowflake-query-tags/blob/main/macros/query_tags.sql#L10) for every model. 
2. To avoid the warning for the `snowplow_web` package, I think you could set the `snowplow__query_tag` var to an empty object `{}`.
3. `query_tag` set in `profiles.yml` is the default query tag. Once a model starts running, dbt overrides that query tag, and then switches it back to the one set in `profiles.yml` once complete. So, no need to change remove the `query_tag` set in `profiles.yml`.

**Comment by bdtoole** [comment]
Thanks, @NiallRees - that helps a lot! I haven't used the term "mapping type" in this context before. Can you clarify what that means?

**Comment by NiallRees** [comment]
That's basically a jinja-ism for a dict or object (`{}`) @bdtoole
