### ISSUE TITLE
Aliasing table reference in cost_per_query and hourly_spend models

### ISSUE THREAD

**Issue by saurasingh** [get-select/dbt-snowflake-monitoring#133]
@NiallRees For the two models in the subject, we need to alias tables like `daily_rates`, 'stg_usage_in_currency_daily', `stg_metering_history`, `stg_serverless_task_history`, and `stg_metering_daily_history`. As the dbt CI adds the schema name as the prefix to the table name. Referencing columns from these tables breaks the object definition as they defer in the names, having an alias name should fix this.

Please refer to the screenshots:

![Screenshot 2023-10-25 at 4 23 41 PM](https://github.com/get-select/dbt-snowflake-monitoring/assets/19628707/640beca2-5990-42f6-84ea-35aebe54fde2)
![Screenshot 2023-10-25 at 4 24 12 PM](https://github.com/get-select/dbt-snowflake-monitoring/assets/19628707/91bd3450-29cb-4de4-bab1-7c6d394734c0)

Tried creating PR to fix this by myself but was not able to commit changes.

**Comment by ernestoongaro** [comment]
Looks like my PR [here](https://github.com/get-select/dbt-snowflake-monitoring/pull/139) would fix this as well

**Comment by saurasingh** [comment]
Thanks for working on it @ernestoongaro. Do you have a steps on how did you contribute to the repo? I was strugling to setup in locally.

**Comment by NiallRees** [comment]
Think this is now resolved! Let me know if 4.6.0 doesn't fix this for you @saurasingh
