### ISSUE TITLE
Add in Snowflake's new `query_parameterized_hash` column

### ISSUE THREAD

**Issue by sidhreddy** [get-select/dbt-snowflake-monitoring#136]
Add in Snowflake's new `query_parameterized_hash` column

Docs: https://docs.snowflake.com/en/user-guide/query-hash

**Comment by ian-whitestone** [comment]
Hey @sidhreddy, thanks for opening the issue!

Agree this would be great to add in. Are you willing to make a contribution? This should be a quick change, would just need to add it to `stg_query_history` and `query_history_enriched`

**Comment by sidhreddy** [comment]
@ian-whitestone I just tried to push a change to address this and am getting 403. I am guessing the repo settings are not allowing folks outside your team to contribute.

**Comment by sidhreddy** [comment]
@ian-whitestone Can you look into this [PR](https://github.com/get-select/dbt-snowflake-monitoring/pull/137).
