### ISSUE TITLE
`dbt_queries` incremental fails unique key (dupes in stg_query_history)

### ISSUE THREAD

**Issue by austintidmoreplace** [get-select/dbt-snowflake-monitoring#144]
Possibly caused by an issue further upstream, incremental runs of `dbt_queries` fail with the error: `Duplicate row detected during DML action.` Digging into the data a bit I find that the expected unique key of `query_id` and `start_time` does not jive with data in the preceding model: `query_history_enriched.` In other words, I find repeated values of the supposed unique key in this table.

**Comment by ian-whitestone** [comment]
hey @austintidmoreplace do you also see the duplicate queries in `stg_query_history`?

**Comment by austintidmoreplace** [comment]
Yes @ian-whitestone, sure do

**Comment by ian-whitestone** [comment]
Any chance you'd be free to hop on a 10 min call this week? Would love to get to the bottom of this and will be easier to discuss live. Here's [my availability](https://calendly.com/ian-at-select/30min)

**Comment by ian-whitestone** [comment]
Closing this out, the reason for dupes was multiple queries inserting records into `stG_query_history` simultaneously due to orchestration issues
