### ISSUE TITLE
Query comment not parsed in query_history_enriched

### ISSUE THREAD

**Issue by grahamwetzler** [get-select/dbt-snowflake-monitoring#147]
`query_history_enriched` does not properly parse the query comment if the first key/value is not `"app": "dbt"` as is the case when using the `extra` parameter in the [`dbt_snowflake_query_tags.get_query_comment` macro](https://github.com/get-select/dbt-snowflake-query-tags/blob/4b30044292793bbdba919f67b2d32b675283843b/macros/query_comment.sql#L2).

https://github.com/get-select/dbt-snowflake-monitoring/blob/e084b35b4b98d195c175143566ea9bf39c218261/models/query_history_enriched.sql#L15

I wasn't sure where to make this issue since I guess this could be fixed in either package.

**Comment by NiallRees** [comment]
Thanks @grahamwetzler - makes sense to fix here, thanks a lot for raising, we'll get this sorted asap.
