### ISSUE TITLE
Probably broken after latest changes in RATE_SHEET_DAILY

### ISSUE THREAD

**Issue by littleK0i** [get-select/dbt-snowflake-monitoring#149]
Snowflake rolled the update for system views, especially for RATE_SHEET_DAILY:
https://docs.snowflake.com/en/release-notes/2024/8_12#organization-usage-improved-views-for-billing-reconciliation-general-availability

For example, service type `COMPUTE` is now `WAREHOUSE_METERING`. I suspect this model requires an update as well.

Thank you.

**Comment by ian-whitestone** [comment]
hey @littleK0i thanks for flagging this!

we've actually accounted for this change already: https://github.com/get-select/dbt-snowflake-monitoring/blob/main/models/staging/stg_rate_sheet_daily.sql as we noticed things breaking a few months ago when Snowflake started rolling this out to newer accounts.

Long term, we will likely update this to keep the service types un-transformed and account for scenarios where Snowflake gives someone a different credit price for automatic clustering vs. compute (worth mentioning we've never seen this to date for any Snowflake customers).
