### ISSUE TITLE
Package not working

### ISSUE THREAD

**Issue by lijol** [get-select/dbt-snowflake-monitoring#45]
I added the as specified 

query-comment:
  comment: '{{ dbt_snowflake_monitoring.get_query_comment(node) }}'
  append: true # Snowflake removes prefixed comments.

models:
  dbt_snowflake_monitoring:
    +schema: "MONITOR"

Can you please tell me what am I missing ? It does seems the model is not running

**Comment by lijol** [comment]
Thanks @ian-whitestone able to run the models

**Comment by ian-whitestone** [comment]
For anyone interested, you can test out running the models in the package specifically by running:

`dbt run -select dbt_snowflake_monitoring`

see model syntax selection docs for more details: https://docs.getdbt.com/reference/node-selection/syntax#examples
