### ISSUE TITLE
Package errors when quoting=true

### ISSUE THREAD

**Issue by cristianivanoff** [get-select/dbt-snowflake-monitoring#52]
I get an error on daily_spend. We have quoting:true and schemas and tables are created in lower/upper case. I need to give the tables an alias to get it to work.

Error:
15:53:53  Snowflake adapter: Snowflake error: 000904 (42000): SQL compilation error: error line 210 at position 45
invalid identifier 'STG_METERING_HISTORY.START_TIME'
15:53:53  finished collecting timing info
15:53:53  On model.dbt_snowflake_monitoring.daily_spend: Close
15:53:54  Database Error in model daily_spend (models/daily_spend.sql)
  000904 (42000): SQL compilation error: error line 210 at position 45
  invalid identifier 'STG_METERING_HISTORY.START_TIME'
  compiled Code at target/run/dbt_snowflake_monitoring/models/daily_spend.sql
15:53:54  Sending event: {'category': 'dbt', 'action': 'run_model', 'label': '5f427b14-9af6-412e-bce6-bdeac404e537', 'context': [<snowplow_tracker.self_describing_json.SelfDescribingJson object at 0x7fa4de6b3310>]}
15:53:54  13 of 17 ERROR creating sql table model SNOWFLAKE_MONITORING.dbt_ci_MONITORING.daily_spend  [ERROR in 2.41s]
15:53:54  Finished running node model.dbt_snowflake_monitoring.daily_spend

**Comment by NiallRees** [comment]
Hi @cristianivanoff please can you share the failed, compiled SQL so we can better investigate? For what it’s worth, I’d highly recommend against using quoted identifiers as they lead to all kinds of issues.

**Comment by michelr** [comment]
Hi @NiallRees, we also, unfortunately, use quoted identifiers. I managed to run locally if I changed the following things:
In 
`cost_per_query`:
- Add alias `daily_rates` for `{{ ref('daily_rates') }}` (2 rows to be fixed)

`hourly_spend`:
- Add alias `daily_rates` for `{{ ref('daily_rates') }}` (11 rows to be fixed)
- Add alias `stg_metering_history` for `{{ ref('stg_metering_history') }}`  (8 rows to be fixed)
- Add alias `stg_serverless_task_history` for `{{ ref('stg_serverless_task_history') }}` (1 row to be fixed)
- Add alias `stg_metering_daily_history` for `{{ ref('stg_metering_daily_history') }}` (2 row to be fixed)

Amazing if you could fix this for next release so we can use your great models in production!
