### ISSUE TITLE
Properly account for overage rates

### ISSUE THREAD

**Issue by ian-whitestone** [get-select/dbt-snowflake-monitoring#55]
The logic introduced to solve https://github.com/get-select/dbt-snowflake-monitoring/issues/23 in https://github.com/get-select/dbt-snowflake-monitoring/pull/24 is causing issues. Example logic from #24 (pattern is repeated throughout):

```sql
compute_rates as (
    select
        date,
        max(effective_rate) as effective_rate
    from {{ ref('daily_rates') }}
    where
        service_type = 'COMPUTE'
        and usage_type in ('compute', 'overage-compute') {# TODO work out how to account for these two types in the event they both occur on a day #}
    group by 1
),
```

The `daily_rates` model ensures there is 1 row per day per usage type per service type. It fills in missing values by using the most recent rate.

As a result, the `compute_rates` CTE example from above will always pick the higher rate (usually `overage`), even if the account wasn't in overage on the particular day. 

**Proposed Solution**

To solve this, we can check the `remaining_balance_daily` view which shows whether someone is in overage or not. based on that, we can pick the correct rate for that day.

**Comment by john-jerome** [comment]
Hey Ian, I was literally just about to report this issue!
I'm also surprised that nobody encountered it before - I believe the total number will only be correct if your `compute` and `overage-compute` rates are the same.

**Comment by ian-whitestone** [comment]
hey @john-jerome apologies for this. We had tested it thoroughly on multiple accounts, but none of them had had `overage` rates before, so we didn't pick this up.

this issue will only appear for Snowflake customers who have exceeded their contract before, or are on-demand.

I'll have a fix shipped today.

**Comment by john-jerome** [comment]
hey @ian-whitestone, thanks for looking into it so promptly!

> this issue will only appear for Snowflake customers who have exceeded their contract before, or are on-demand.

In our case, the latest available rate for `overage-compute` was back in March 2022, but since the `daily_rates` model extrapolates the rates we now have this record for each day up until yesterday. This makes me wonder if another addition to the fix you suggested above could be to completely exclude all `overage` rates from being extrapolated, wdyt?

**Comment by ian-whitestone** [comment]
> This makes me wonder if another addition to the fix you suggested above could be to completely exclude all overage rates from being extrapolated, wdyt?

Good suggestion. 

We could do that as well, but my proposed solution will still be required since there will always be two rates (`overage-compute` and `compute`) when an account is in overage. 

I'm gonna start with that and see if it's sufficient, to avoid adding too much additional complexity to `daily_rates`

**Comment by john-jerome** [comment]
Sounds good!
also happy to test the fix on our account before you release it, just ping me in this thread :)
