### ISSUE TITLE
Improve developer experience

### ISSUE THREAD

**Issue by ian-whitestone** [get-select/dbt-snowflake-monitoring#6]
* Add a Python development environment with poetry
* Add pre-commit and run SQLfluff before committing

Right now the process is shitty with:

1. Push to branch
2. Request CI tests to run
3. Fails due to sql fluff linting rules
4. Repeat

**Comment by ian-whitestone** [comment]
@NiallRees we should also explain what environment variables need to be set in `.zshenv` so that users can run integration tests locally on their own snowflake account if desired

**Comment by ian-whitestone** [comment]
Some work done in #7

**Comment by NiallRees** [comment]
I also added instructions on running the integration tests. What env vars are needed?
