### ISSUE TITLE
Query History Enriched doesn't work with a custom target schema

### ISSUE THREAD

**Issue by PedramNavid** [get-select/dbt-snowflake-monitoring#82]
Hi friends, great package! Found an odd bug related to the `query_history_enriched` model.

Specifically: https://github.com/get-select/dbt-snowflake-monitoring/blob/2a6179ee3bc53a9092b4aa36ed6febcdff21ee0b/models/query_history_enriched.sql#L13

However, it looks like `target.schema` uses the default schema for the profile, and not the schema for the package. 

In my `dbt_project.yml` I tried to set a custom schema for this package, since I wanted these models to go under `eng`.

```yml
models:
  dbt_internal:
    marts:
      +materialized: table
      core:
        +schema: core
    ...
  github_source:
    +schema: staging
  github:
    +schema: eng
  dbt_snowflake_monitoring:
    +schema: eng
```

However, when running dbt I get a Snowflake access error. Inspectng the compiled model sheds some light on this:

```sql
with
query_history as (
    select
        *,

        -- this removes comments enclosed by /* <comment text> */ and single line comments starting with -- and either ending with a new line or end of string
        analytics.dbt.dbt_snowflake_monitoring_regexp_replace(query_text, ....  /* NOTE: this is the wrong target schema! */

        ....

    from analytics.eng.stg_query_history /* NOTE: This is the right target schema! */ 


),

cost_per_query as (
    select *
    from analytics.eng.cost_per_query

)
```

I wonder if you should be using `generate_schema_name` rather than `target.schema` as mentioned here: https://docs.getdbt.com/docs/build/custom-schemas

When removing the custom schema in dbt_project.yml, everything works fine, so my hunch is that it has to do with that one parameter.

-----------

```
dbt --version
Core:
  - installed: 1.3.0
  - latest:    1.4.1 - Update available!

  Your version of dbt-core is out of date!
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

Plugins:
  - snowflake: 1.3.0 - Update available!

  At least one plugin is out of date or incompatible with dbt-core.
  You can find instructions for upgrading here:
  https://docs.getdbt.com/docs/installation

```

**Comment by NiallRees** [comment]
Hey @PedramNavid thanks for opening this - would you be able to check if the linked PR solves it? I've tested it and it seems to but want to make sure.
