### ISSUE TITLE
dbt_queries.sql - Unknown functions VAR, VAR

### ISSUE THREAD

**Issue by rossserven** [get-select/dbt-snowflake-monitoring#89]
looks like these should be Jinja variables:
`'{{ var('dbt_cloud_url', 'https://cloud.getdbt.com/deploy/') }}'`

https://github.com/get-select/dbt-snowflake-monitoring/blob/fd5f8dc9036ee5615540d5feaf3c03c1d8d25be2/models/dbt_queries.sql#L35

https://github.com/get-select/dbt-snowflake-monitoring/blob/fd5f8dc9036ee5615540d5feaf3c03c1d8d25be2/models/dbt_queries.sql#L44

**Comment by NiallRees** [comment]
Thanks @rossserven!

**Comment by NiallRees** [comment]
This is now fixed in 3.0.1.
