### ISSUE TITLE
Specify schema to place dbt-snowflake-monitoring objects

### ISSUE THREAD

**Issue by mjahammel** [get-select/dbt-snowflake-monitoring#93]
dbt-snowflake-monitoring places it's objects in the schema defined in the profiles.yml file.  Is there any way to specify an alternative schema name for those objects?

Thanks,

**Comment by NiallRees** [comment]
Hey @mjahammel - this is covered in the dbt docs so we won't repeat here. Glad you got it sorted! 

https://docs.getdbt.com/docs/build/packages#configuring-packages
