### ISSUE TITLE
Silly Question:  How do you create the models with the query data?

### ISSUE THREAD

**Issue by dweaver33** [get-select/dbt-snowflake-monitoring#94]
I got the package installed and the query tags working.  However, I'm missing the step where we create the database to contain the model data.  

Do I just create that in Snowflake and the macro will build out the models?  

Silly question...I know.

**Comment by dweaver33** [comment]
Figured it out.  You just run with
`dbt run -t [environment] -m dbt_snowflake_monitoring`

What's the best practice here?  Create a `dbt_snowflake_monitoring` database and put all data into a single schema?  Schema per environment?

**Comment by ian-whitestone** [comment]
@dweaver33 thanks for opening the issue! Sounds like you got it sorted. We will update our docs in the meantime to include instructions on how users typically run the package.

> What's the best practice here?

It really varies customer to customer, but I would say most just do a nightly `dbt run` which runs all models in their project and the installed packages (including ours).

> Create a dbt_snowflake_monitoring database and put all data into a single schema? Schema per environment?

I think it really comes down to your preference. I'd say most companies will have models from packages live in the same database as the rest of the dbt models in their project. Customers will typically have separate databases per environment (i.e. development versus production).

In terms of putting our package in a separate schema within your database, some keep it the same and others separate - see #93 for an example of how to do that.

Hope that helps!
